server:
  http_listen_port: 3200
  log_level: info

distributor:
  rate_limit_enabled: true
  rate_limit: 20000

ingester:
  max_block_duration: 5m

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

metrics_generator:
  processor:
    batch:
      timeout: 5s
      send_batch_size: 100
  storage:
    path: /var/tempo/generator/wal

querier:
  frontend_address: http://grafana:3000
  max_concurrent_requests: 20

frontend:
  compression: snappy
  max_cache_freshness_per_query: 5m
