#!/usr/bin/env python3
"""Validate the supply-chain guardrails that can be checked without Docker."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PINNED_IMAGE_FILES = [
    ROOT / "docker-compose.yml",
    ROOT / "docker-compose.dev.yaml",
]
FLOATING_TAGS = {"latest", "stable", "edge", "main", "master", "dev"}
IMAGE_RE = re.compile(r"^\s*image:\s*([^\s#]+)", re.MULTILINE)


def image_tag(image: str) -> str | None:
    """Return the tag portion of an image reference, ignoring registry ports."""
    last_slash = image.rfind("/")
    last_colon = image.rfind(":")
    if last_colon <= last_slash:
        return None
    return image[last_colon + 1 :]


def validate_images() -> list[str]:
    errors: list[str] = []
    for path in PINNED_IMAGE_FILES:
        if not path.exists():
            errors.append(f"missing pinned-image file: {path.relative_to(ROOT)}")
            continue
        for match in IMAGE_RE.finditer(path.read_text()):
            image = match.group(1).strip('"\'')
            tag = image_tag(image)
            if tag is None:
                errors.append(f"{path.relative_to(ROOT)}: image {image!r} has no explicit tag")
            elif tag in FLOATING_TAGS or tag.endswith("-latest"):
                errors.append(f"{path.relative_to(ROOT)}: image {image!r} uses floating tag {tag!r}")
    return errors


def validate_lockfile() -> list[str]:
    lockfile = ROOT / "poetry.lock"
    pyproject = ROOT / "pyproject.toml"
    errors: list[str] = []
    if not lockfile.exists():
        errors.append("poetry.lock is missing")
    if not pyproject.exists():
        errors.append("pyproject.toml is missing")
    if lockfile.exists():
        head = lockfile.read_text(errors="ignore")[:200]
        if "@generated by Poetry" not in head:
            errors.append("poetry.lock does not look like a Poetry-generated lockfile")
    return errors


def main() -> int:
    errors = validate_images() + validate_lockfile()
    if errors:
        print("Supply-chain validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("Supply-chain validation passed: core Docker images are pinned and poetry.lock is committed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
